# Generated by Django 4.1.6 on 2023-04-24 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('last_price', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
                ('broker', models.CharField(max_length=30)),
                ('monitor', models.BooleanField(default=False)),
                ('presision', models.IntegerField(blank=True, null=True)),
                ('scale', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.IntegerField(blank=True, null=True)),
                ('side', models.CharField(blank=True, max_length=100, null=True)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('tp', models.FloatField(blank=True, null=True)),
                ('sl', models.FloatField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Openposition', to='copy_traider.symbols')),
            ],
        ),
        migrations.CreateModel(
            name='OpenOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('tp', models.FloatField(blank=True, null=True)),
                ('sl', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=600, null=True)),
                ('active', models.BooleanField(default=True)),
                ('return_object', models.CharField(blank=True, max_length=600, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OpenOrder', to='copy_traider.symbols')),
            ],
        ),
    ]
